In [9]:
import pandas as pd
movies = pd.read_csv("movies.csv")

In [10]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
62418,209157,We (2018),Drama
62419,209159,Window of the Soul (2001),Documentary
62420,209163,Bad Poems (2018),Comedy|Drama
62421,209169,A Girl Thing (2001),(no genres listed)
62422,209171,Women of Devil's Island (1962),Action|Adventure|Drama

In [11]:
import re
def clean_title(title):
    return re.sub("[^a-zA-Z0-9 ]", "", str(title))

In [12]:
movies["clean_title"] = movies["title"].apply(clean_title)

In [13]:
movies

,movieId,title,genres,clean_title
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Toy Story 1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,Jumanji 1995
2,3,Grumpier Old Men (1995),Comedy|Romance,Grumpier Old Men 1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Waiting to Exhale 1995
4,5,Father of the Bride Part II (1995),Comedy,Father of the Bride Part II 1995
...,...,...,...,...
62418,209157,We (2018),Drama,We 2018
62419,209159,Window of the Soul (2001),Documentary,Window of the Soul 2001
62420,209163,Bad Poems (2018),Comedy|Drama,Bad Poems 2018
62421,209169,A Girl Thing (2001),(no genres listed),A Girl Thing 2001
62422,209171,Women of Devil's Island (1962),Action|Adventure|Drama,Women of Devils Island 1962

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(ngram_range=(1,2))
tfidf = vectorizer.fit_transform(movies["clean_title"])

In [15]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def search(title):
    title = clean_title(title)
    query_vec = vectorizer.transform([title])
    similarity = cosine_similarity(query_vec, tfidf).flatten()
    indices = np.argpartition(similarity, -5)[-5:]
    results = movies.iloc[indices][::-1]
    return results

In [ ]:
import ipywidgets as widgets
from IPython.display import display

movies_input = widgets.Text(
    value="The Avengers",
    description="Movie title:",
    disabled=False
)
movie_list = widgets.Output()

def on_type(change):
 with movie_list:
    movie_list.clear_output()
    title = change["new"]
    if len(title) > 2:
        display(search(title))
        pass

movies_input.observe(on_type, names='value')

display(movies_input, movie_list)
with movie_list:
 display(search(movies_input.value))

Text(value='The Avengers', description='Movie title:')

Output()

In [51]:
ratings =pd.read_csv("ratings.csv")

In [52]:
ratings

          userId  movieId  rating   timestamp
0              1      296     5.0  1147880044
1              1      306     3.5  1147868817
2              1      307     5.0  1147868828
3              1      665     5.0  1147878820
4              1      899     3.5  1147868510
...          ...      ...     ...         ...
25000090  162541    50872     4.5  1240953372
25000091  162541    55768     2.5  1240951998
25000092  162541    56176     2.0  1240950697
25000093  162541    58559     4.0  1240953434
25000094  162541    63876     5.0  1240952515

[25000095 rows x 4 columns]

In [53]:
ratings.dtypes

userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

In [54]:
movie_id = 1

In [66]:
similar_users = ratings[(ratings["movieId"] == movie_id) & (ratings["rating"] >= 5)]["userId"].unique()

In [67]:
similar_users

array([    36,     75,     86, ..., 162518, 162519, 162530],
      shape=(13506,))

In [68]:
similar_user_recs = ratings[(ratings["userId"].isin(similar_users)) & (ratings["rating"] > 4)]

In [69]:
similar_user_recs

          userId  movieId  rating  timestamp
5101          36        1     5.0  857131378
5105          36       34     5.0  834413787
5111          36      110     5.0  834412999
5114          36      150     5.0  839928587
5127          36      260     5.0  857131062
...          ...      ...     ...        ...
24998388  162530     3706     5.0  989809041
24998389  162530     3735     5.0  989808150
24998391  162530     3763     5.0  989809659
24998392  162530     4187     5.0  989809274
24998393  162530     4321     5.0  989807602

[912084 rows x 4 columns]